[tool.poetry]
name = "temporal-trivia-ui"
version = "0.1.0"
description = "Temporal Trivia UI"
authors = ["ktenzer <keith.tenzer@temporal.io>"]

[tool.poetry.dependencies]
python = "^3.11"
flask = {extras = ["async"], version = "^2.2.3"}
qrcode = "^7.4.2"
flask-session = "^0.5.0"
dnspython = "^2.4.2"

[tool.poetry.group.encryption]
optional = true
dependencies = { cryptography = "^38.0.1", aiohttp = "^3.8.1" }

[tool.poetry.group.dev.dependencies]
temporalio = "^1.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
